// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzM4ENKggkV8I_sBfCxXpQOOp5KjnGwKU',
    appId: '1:82870674788:web:314db4eb873a28cfd98671',
    messagingSenderId: '82870674788',
    projectId: 'howard-9d223',
    authDomain: 'howard-9d223.firebaseapp.com',
    storageBucket: 'howard-9d223.appspot.com',
    measurementId: 'G-6SH3QBQ52V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhhTesKKuP97AyWICa-OWBHgpWwYbgl_4',
    appId: '1:82870674788:android:d8b130981dc06e26d98671',
    messagingSenderId: '82870674788',
    projectId: 'howard-9d223',
    storageBucket: 'howard-9d223.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTq8aIaWIv0YadODsu_GKKu8kliODQDbE',
    appId: '1:82870674788:ios:ec7a94786e0f5417d98671',
    messagingSenderId: '82870674788',
    projectId: 'howard-9d223',
    storageBucket: 'howard-9d223.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTq8aIaWIv0YadODsu_GKKu8kliODQDbE',
    appId: '1:82870674788:ios:ec7a94786e0f5417d98671',
    messagingSenderId: '82870674788',
    projectId: 'howard-9d223',
    storageBucket: 'howard-9d223.appspot.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzM4ENKggkV8I_sBfCxXpQOOp5KjnGwKU',
    appId: '1:82870674788:web:4fe94fe131a8b24ed98671',
    messagingSenderId: '82870674788',
    projectId: 'howard-9d223',
    authDomain: 'howard-9d223.firebaseapp.com',
    storageBucket: 'howard-9d223.appspot.com',
    measurementId: 'G-K7NK0M9KDH',
  );

}